runtime: go
api_version: go1.9

handlers:
- url: /backend/.*
  script: _go_app

#[START env]
env_variables:
  POSTGRESQL_USERNAME: "USERNAME"
  POSTGRESQL_PASSWORD: "PASSWORD"
  POSTGRESQL_PLAYERDATABASE: "DATABASE"
  POSTGRESQL_LOCATION: "host=/cloudsql/ilutulestikud-191419:europe-west3:ilutulestikud-postgresql"
#[END env]

#[START cloudsql_settings]
beta_settings:
  cloud_sql_instances: ilutulestikud-191419:europe-west3:ilutulestikud-postgresql
#[END cloudsql_settings]